[package]
name = "reflex-rison"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ansi_term = "0.12.1"
term_size = "0.3.2"